version: 1
update_configs:
  - package_manager: "submodules"
    directory: "./"
    update_schedule: "daily"
    allowed_updates:
      - match:
          dependency_name: "1-zishkaz"
      - match:
          dependency_name: "1-Ramazanov-Amir"
      - match:
          dependency_name: "1-MashrurIslam"
      - match:
          dependency_name: "1-rudolf101"
    ignored_updates:
      - match:
          dependency_name: "1-grading-tests"
