version: 1
update_configs:
  - package_manager: "submodules"
    directory: "./"
    update_schedule: "daily"
    allowed_updates:
      - match:
          dependency_name: "1-DelRoso"
      - match:
          dependency_name: "1-SofuriHafe"
      - match:
          dependency_name: "1-foreverjun"
      - match:
          dependency_name: "1-esvault"
      - match:
          dependency_name: "1-TheDarkRisen"
      - match:
          dependency_name: "1-TimPushkin"
      - match:
          dependency_name: "1-ToTTopBYxe"
      - match:
          dependency_name: "1-kettlberry"
      - match:
          dependency_name: "1-danielsheh02"
      - match:
          dependency_name: "1-zishkaz"
      - match:
          dependency_name: "1-Ramazanov-Amir"
      - match:
          dependency_name: "1-MashrurIslam"
      - match:
          dependency_name: "1-rudolf101"
    ignored_updates:
      - match:
          dependency_name: "1-grading-tests"
